hey, deps work

diff --git a/smake b/smake
--- a/smake
+++ b/smake
@@ -33,22 +33,30 @@ while getopts "C:o:f:j:gh" o; do
 done
 shift $((OPTIND - 1))
 
+smakecmd="$(readlink -f "$0")"
 cd "$opt_path"
 
-if [ -f Makefile ] && ! head -n 1 Makefile | grep "Makefile generated by Smake." >/dev/null; then
-	echo "Makefile isn't generated by smake; refusing to overwrite."
-	echo "To run smake, manually move or delete the existing Makefile."
+if [ -f Makefile ] && ! head -n 1 Makefile | grep "Makefile generated by smake." >/dev/null; then
+	echo "Makefile isn't generated by smake; refusing to overwrite." >&2
+	echo "To run smake, manually move or delete the existing Makefile." >&2
 	exit 1
 fi
 
-if [ -n "$MAKE" ]; then
-	make="$MAKE"
+if [ -n "$MAKE" ]; then make="$MAKE"
 elif make="$(command -v gmake)"; then :
 elif make="$(command -v make)"; then :
 else
-	echo "Neither 'gmake' nor 'make' was found. Either install make or set \$MAKE."
+	echo "Neither 'gmake' nor 'make' was found. Either install make or set \$MAKE." >&2
 	exit 1
 fi
+
+islib() {
+	[ "$1" = solib ] || [ "$1" = alib ] || [ "$1" = lib ]
+}
+
+isexec() {
+	[ "$1" = exec ]
+}
 
 # A somewhat ugly way to get a variable from the Smakefile,
 # but at least we're using make's parser
@@ -69,10 +77,11 @@ dumpvar:
 }
 
 # Get some variables from the Smakefile
+smakedeps="$(getvar SMAKEDEPS "")"
 target="$(getvar TARGET "$(basename "$(readlink -f .)")")"
 projtype="$(getvar PROJTYPE exe)"
 if ! echo " exe solib alib lib " | grep " $projtype " >/dev/null; then
-	echo "Invalid projtype: $projtype. Expected exe, lib, alib or solib."
+	echo "Invalid PROJTYPE: $projtype. Expected exe, lib, alib or solib." >&2
 	exit 1
 fi
 
@@ -82,36 +91,71 @@ if [ -d src ]; then
 	headers="$(find src -name '*.h')"
 fi
 if [ -d include ]; then
-	headers="$headers$(find include -name '*.h')"
+	publicheaders="$(find include -name '*.h')"
+	headers="$headers$publicheaders"
 fi
 srcs="$(printf "%s" "$sources" | tr '\n' ' ')"
 hdrs="$(printf "%s" "$headers" | tr '\n' ' ')"
+publichdrs="$(printf "%s" "$publicheaders" | tr '\n' ' ')"
+smakedeptargets=""
+
+# Flags
+ccopts="-Iinclude"
+ldopts=""
+deptargets=""
+if islib "$projtype"; then
+	ccopts="$ccopts -fPIC"
+fi
+
+# Find dependencies
+for dep in $smakedeps; do
+	depdeps="$($smakecmd -C "$dep" PREPEND="$dep/" dumpdeps)"
+	deppublicdeps="$($smakecmd -C "$dep" PREPEND="$dep/" dumppublicdeps)"
+	deptype="$($smakecmd -C "$dep" dumpprojtype)"
+	extradeps="$extradeps $depdeps"
+	extrapublicdeps="$extrapublicdeps $deppublicdeps"
+
+	smakedeptargets="$smakedeptargets $dep/build/\$(CONFIG)/.built"
+	deptargets="$deptargets
+$dep/build/\$(CONFIG)/.built: $depdeps
+	\$(MAKE) -C $dep"
+
+	if islib "$deptype"; then
+		ccopts="$ccopts -isystem $dep/include"
+		ldopts="$ldopts -L$dep/build/\$(CONFIG)"
+	fi
+done
 
 mk_target_exe() {
 echo "\
-\$(BUILD)/\$(TARGET): \$(OBJS) \$(EXTRADEPS)
+\$(BUILD)/\$(TARGET): $smakedeptargets \$(OBJS) \$(EXTRADEPS)
 	@mkdir -p \$(@D)
 	\$(CC) -o \$@ \$(OBJS) \$(LDFLAGS)
-	@echo Compiled \$@."
+	touch \$(BUILD)/.built
+	@echo Created \$@."
 }
 
 mk_target_solib() {
 echo "\
-\$(BUILD)/\$(TARGET).so: \$(OBJS) \$(EXTRADEPS)
+\$(BUILD)/\$(TARGET).so: $smakedeptargets \$(OBJS) \$(EXTRADEPS)
 	@mkdir -p \$(@D)
 	\$(CC) -o \$@ \$(OBJS) -shared \$(LDLAGS)
-	@echo Compiled \$@."
+	touch \$(BUILD)/.built
+	@echo Created \$@."
 }
 
 mk_target_alib() {
 echo "\
-\$(BUILD)/\$(TARGET).a: \$(OBJS) \$(EXTRADEPS)
+\$(BUILD)/\$(TARGET).a: $smakedeptargets \$(OBJS) \$(EXTRADEPS)
 	@mkdir -p \$(@D)
 	\$(AR) crs \$@ \$(OBJS)
-	@echo Compiled \$@."
+	touch \$(BUILD)/.built
+	@echo Created \$@."
 }
 
 mk_target_lib() {
+	echo "all: \$(BUILD)/\$(TARGET).so \$(BUILD)/\$(TARGET).a"
+	echo
 	mk_target_solib
 	echo
 	mk_target_alib
@@ -146,13 +190,13 @@ install: \$(BUILD)/\$(TARGET).so
 	mkdir -p \$(DESTDIR)\$(PREFIX)/lib
 	cp -f \$^ \$(DESTDIR)\$(PREFIX)/lib
 	chmod 755 \$(DESTDIR)\$(PREFIX)/lib/\$(TARGET).so
-	mkdir -p \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)
-	cp -rf include/* \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)
+	mkdir -p \$(DESTDIR)\$(PREFIX)/include
+	cp -rf include/* \$(DESTDIR)\$(PREFIX)/include
 
 .PHONY: uninstall
 uninstall:
 	rm -f \$(DESTDIR)\$(PREFIX)/lib/\$(TARGET).so
-	rm -rf \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)"
+	rm -rf \$(patsubst include/%,\$(DESTDIR)\$(PREFIX)/include/%,\$(wildcard include/*))"
 }
 
 mk_installation_alib() {
@@ -161,13 +205,13 @@ echo "\
 install: \$(BUILD)/\$(TARGET).a
 	mkdir -p \$(DESTDIR)\$(PREFIX)/lib
 	cp -f \$^ \$(DESTDIR)\$(PREFIX)/lib
-	mkdir -p \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)
-	cp -rf include/* \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)
+	mkdir -p \$(DESTDIR)\$(PREFIX)/include
+	cp -rf include/* \$(DESTDIR)\$(PREFIX)/include
 
 .PHONY: uninstall
 uninstall:
 	rm -f \$(DESTDIR)\$(PREFIX)/lib/\$(TARGET).a
-	rm -rf \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)"
+	rm -rf \$(patsubst include/%,\$(DESTDIR)\$(PREFIX)/include/%,\$(wildcard include/*))"
 }
 
 mk_installation_lib() {
@@ -176,14 +220,14 @@ echo "\
 install: \$(BUILD)/\$(TARGET).so \$(BUILD)\$(TARGET).a
 	mkdir -p \$(DESTDIR)\$(PREFIX)/lib
 	cp -f \$^ \$(DESTDIR)\$(PREFIX)/lib
-	mkdir -p \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)
-	cp -rf include/* \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)
+	mkdir -p \$(DESTDIR)\$(PREFIX)/include
+	cp -rf include/* \$(DESTDIR)\$(PREFIX)/include
 
 .PHONY: uninstall
 uninstall:
 	rm -f \$(DESTDIR)\$(PREFIX)/lib/\$(TARGET).so
 	rm -f \$(DESTDIR)\$(PREFIX)/lib/\$(TARGET).a
-	rm -rf \$(DESTDIR)\$(PREFIX)/include/\$(INCNAME)"
+	rm -rf \$(patsubst include/%,\$(DESTDIR)\$(PREFIX)/include/%,\$(wildcard include/*))"
 }
 
 mk_installation() {
@@ -196,28 +240,35 @@ mk_installation() {
 }
 
 echo "\
-# Makefile generated by Smake.
+# Makefile generated by smake.
 
 SRCS = $srcs
 HDRS = $hdrs
+PUBLICHDRS = $publichdrs
 
 # Defaults
 PKGS =
 TARGET = $target
 VERSION = $(git describe 2>/dev/null || echo unknown)
 PROJTYPE = $projtype
-EXTRADEPS =
+EXTRADEPS = $extradeps
+EXTRAPUBLICDEPS = $extrapublicdeps
 CONFIG ?= release
-BUILD ?= build/\$(CONFIG)
+BUILDDIR ?= build
+BUILD ?= \$(BUILDDIR)/\$(CONFIG)
 WARNINGS = -Wall -Wextra -Wno-unused-parameter
 SMAKEFILE ?= Smakefile
+PHONIES = dumpdeps dumppublicdeps dumpprojtype clean distclean
 
-CCOPTS = -Iinclude -fPIC
+PKG_CONFIG ?= pkg-config
+AR ?= ar
+
+CCOPTS = $ccopts
 CCOPTS_release = -O2 -flto
 CCOPTS_debug = -g
 CCOPTS_sanitize = -fsanitize=address -fsanitize=undefined \$(CCOPTS_debug)
 
-LDOPTS =
+LDOPTS = $ldopts
 LDOPTS_release = -flto
 LDOPTS_debug =
 LDOPTS_sanitize = -fsanitize=address -fsanitize=undefined \$(LDOPTS_debug)
@@ -231,12 +282,8 @@ LDFLAGS += \$(LDOPTS_\$(CONFIG)) \$(LDOPTS)
 OBJS = \$(patsubst src/%,\$(BUILD)/obj/%.o,\$(SRCS))
 DEPS = \$(patsubst src/%,\$(BUILD)/dep/%.d,\$(SRCS))
 
-PKG_CONFIG ?= pkg-config
-AR ?= ar
-
 DESTDIR ?=
 PREFIX ?= /usr/local
-INCNAME ?= \$(patsubst lib%,%,\$(TARGET))
 
 ifneq (\$(PKGS),)
 CFLAGS += \$(shell \$(PKG_CONFIG) --cflags \$(PKGS))
@@ -245,11 +292,12 @@ LDFLAGS += \$(shell \$(PKG_CONFIG) --libs \$(PKGS))
 endif
 
 $(mk_target)
+$deptargets
 
-\$(BUILD)/obj/%.c.o: src/%.c
+\$(BUILD)/obj/%.c.o: src/%.c \$(EXTRAPUBLICDEPS)
 	@mkdir -p \$(@D)
 	\$(CC) -o \$@ -c \$< \$(CFLAGS)
-\$(BUILD)/obj/%.cc.o: src/%.cc
+\$(BUILD)/obj/%.cc.o: src/%.cc \$(EXTRAPUBLICDEPS)
 	@mkdir -p \$(@D)
 	\$(CXX) -o \$@ -c \$< \$(CXXFLAGS)
 
@@ -266,11 +314,26 @@ $(mk_installation)
 clean:
 	rm -rf \$(BUILD)
 
-ifneq (\$(MAKECMDGOALS),clean)
+.PHONY: distclean
+distclean:
+	rm -rf \$(BUILDDIR)
+
+.PHONY: dumpdeps
+dumpdeps:
+	@echo \$(addprefix \$(PREPEND),\$(SRCS) \$(HDRS) \$(EXTRADEPS))
+
+.PHONY: dumppublicdeps
+dumppublicdeps:
+	@echo \$(addprefix \$(PREPEND),\$(PUBLICHDRS) \$(EXTRAPUBLICDEPS))
+
+.PHONY: dumpprojtype
+dumpprojtype:
+	@echo \$(PROJTYPE)
+
+ifeq (\$(filter \$(PHONIES),\$(MAKECMDGOALS)),)
 -include \$(DEPS)
 endif" > "$opt_output"
 
 if [ "$opt_generate_only" = 0 ]; then
-	echo "$make -j $opt_jobs $*"
-	$make -j "$opt_jobs" SMAKEFILE="$opt_file" -f "$opt_output" "$@"
+	$make SMAKEFILE="$opt_file" -j "$opt_jobs" -f "$opt_output" "$@"
 fi
